site_name: My Project Documentation
site_url: https://tno-terminology-design.github.io/tev2-mve/
theme: material
nav:
  - Home: index.md
  - About: about.md

# Assuming your Markdown files are directly in the /docs folder
docs_dir: docs

# This is where the built site will be output, which GitHub Actions can then deploy
site_dir: site

# Plugins can be added here
plugins:
  - search