site_name: TEv2 MVE for Github Pages
site_url: https://tno-terminology-design.github.io/tev2-mve/
theme: material
nav:
  - Home: index.md
  - How To Install TEv2:
    - Locally: how-to/install-tev2-tools-locally.md
    - In GitHub Actions: how-to/add-tev2-tools-to-actions-script.md
  - How To Manage Files:
    - The SAF: how-to/saf.md
    - Config files: how-to/config-files.md
    - Terms and Definitions: how-to/curated-texts.md
  - How To Run Tools:
    - Generate HRG: how-to/generate-hrgs.md
    - Generate MRGs: how-to/generate-mrgs.md
    - Import MRGs from elsewhere: how-to/import-mrgs.md
    - Resolve TermRefs: how-to/resolve-termrefs.md
  - How To Use Spec-Up Term References: how-to/use-spec-up-term-references.md
  - Glossary: glossary.md
  - Abbreviations: abbreviations.md

# Assuming your Markdown files are directly in the /docs folder
docs_dir: docs

# This is where the built site will be output, which GitHub Actions can then deploy
site_dir: site

# Plugins can be added here
plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
# known pygments_styles: monokai, friendly, colorful, solarized-dark, solarized-light
      pygments_style: solarized-dark 
  - pymdownx.extra
