# TNO Terminology Design tools configuration file (yaml)

## General
scopedir: .          # URL of the scope directory (where the SAF is located)
onNotExist: warn     # Action in case something doesn't exist
output: .            # (root) directory for output files to be written to

## Term Reference Resolution Tool
trrt:
  interpreter: "(?:(?<=[^`])|^)\\[\\[(?:xref:\\s*(?<scopetag>[a-z0-9_-]+),|ref:)\\s*(?<showtext>[^\n\\],]+)\\]\\]"
  converter: html-hovertext-link # style in which TermRefs are to be rendered
  input:                         # glob pattern for files to be processed
    - "**/*.md"