# TNO Terminology Design tools configuration file (yaml)

## General
scopedir: .          # URL of the scope directory (where the SAF is located)
onNotExist: warn     # Action in case something doesn't exist
output: .            # (root) directory for output files to be written to

## Machine Readable Glossary Tool
mrgt:
  vsntag:            # versiontag of MRG to generate. Default: all MRGs

## Human Readable Glossary Tool
hrgt:
  converter[1]: "## [{{#if glossaryTerm}}{{noRefs glossaryTerm}}{{else}}{{capFirst term}}{{/if}}]({{localize navurl}})\n\n{{#if glossaryText}}{{glossaryText}}{{else}}no `glossaryText` was specified for this entry.{{/if}}\n\n{{#if glossaryNotes}}### Notes\n\n{{#each glossaryNotes}}- {{this}}\n{{/each}}\n{{/if}}"
  converter[2]: "{{#if glossaryAbbr}}## [{{glossaryAbbr}}]({{localize navurl}})\n\nSee: [{{#if glossaryTerm}}{{glossaryTerm}}{{else}}{{capFirst term}}{{/if}}]({{termid}}@)\n\n{{else}}{{log level='silent'}}{{/if}}"  # add HRG-entries for abbreviations (i.e. that have a non-empty `glossaryAbbr` field)
  input:                         # glob pattern for files to be processed
    - "*.md"

## Term Reference Resolution Tool
trrt:
  converter: html-hovertext-link # style in which TermRefs are to be rendered
  input:                         # glob pattern for files to be processed
    - "**/*.md"