# TNO Terminology Design tools configuration file (yaml)

## General
scopedir: .          # URL of the scope directory (where the SAF is located)
onNotExist: warn     # Action in case something doesn't exist
output: .            # (root) directory for output files to be written to

## Machine Readable Glossary Tool
mrgt:
  vsntag:            # versiontag of MRG to generate. Default: all MRGs

## Human Readable Glossary Tool
hrgt:
  converter: markdown-section-2  # style in which glossary entries are to be rendered
  input:                         # glob pattern for files to be processed
    - "*.md"

## Term Reference Resolution Tool
trrt:
  converter: html-hovertext-link # style in which TermRefs are to be rendered
  input:                         # glob pattern for files to be processed
    - "**/*.md"